### PR TITLE
Add proper windows support with default config

### PR DESCRIPTION
**Pull request by BrendonSled**
This fixes issue #404

### CODE REVIEW

**Comment by dochathuc** [comment]
@BrendonSled You save my life. Thanks

**Comment by BrendonSled** [comment]
@HazAT mind reviewing? My team is having to use a fork to get windows compatibility

**Comment by OleksandrKucherenko** [comment]
@Titozzz can you take a look? ^

**Comment by Titozzz** [comment]
Why me 🤔? I'm no windows expert 😛 .

Code looks fine tho.

**Pull request merged**
