### PR TITLE
Cocoapods support

### PR DESCRIPTION
**Pull request by HazAT**
~~This is currently on hold because there are a few open issues with react-native itself.
https://github.com/facebook/react-native/pull/12089#issuecomment-276654535
Waiting for 0.43 release.~~

### CODE REVIEW

**Comment by oblador** [comment]
Hi, I believe your issue is unrelated. It works with React Native 0.42 if you also add `s.dependency 'React'`.

**Comment by HazAT** [comment]
I am pretty sure you will get an ancient version of react if you do this ...
http://cocoapods.org/pods/react
It's marked as deprecated ... the new way of installing react as a pod is ...
`npm install react-native`

And then in your `Podfile`
```
pod 'React', :path => './node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
      # Add any other subspecs you want to use in your project
    ]
```

**Comment by oblador** [comment]
Hi, yeah, you have to do that in your main Podfile then this podspec would use that one. If you haven't defined that one then yes it'd download version 0.11 or similar from the cocoapods repo.

**Comment by oblador** [comment]
I guess there's no way around using CocoaPods for RN if you want to use it for other dependencies that depend on RN. And if you aren't using the local node-modules version then it won't work anyway.

**Comment by oblador** [comment]
The PR you're referencing seems to be released in 0.42 already btw: https://github.com/facebook/react-native/commit/2981560e400c0e4982e992c582d08fef4edb1cde

**Comment by HazAT** [comment]
I am getting this error ...
screen shot 2017-03-21 at 17 46 38
Haven't found a fix for it yet ... Changing the Header Search Paths doesn't do anything.

**Comment by oblador** [comment]
Adding `s.dependency 'React'` fixes that error for me :-)

**Comment by HazAT** [comment]
@oblador Thx that actually works 💯 
Will finish the PR tomorrow ...

**Pull request merged**
